# We don't specify a global language both because we use different
# languages in different jobs, and because in some cases travis
# language-specific automation either does things we don't want to do,
# or does them too early in the process, i.e. lein deps, etc.  It's
# still possible to set the language explicitly for a job when that's
# appropriate.
language: generic

dist: xenial

# Always explicitly set sudo.  Otherwise travis' defaults may vary
# based on when the repository testing was enabled.
sudo: required

aliases:
  - &before-docker-tests
    - sudo rm /usr/local/bin/docker-compose
    - curl --location https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname --kernel-name`-`uname --machine` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - mkdir -vp ~/.docker/cli-plugins
    - curl --location https://github.com/docker/buildx/releases/download/v${DOCKER_BUILDX_VERSION}/buildx-v${DOCKER_BUILDX_VERSION}.linux-amd64 > ~/.docker/cli-plugins/docker-buildx
    - chmod +x ~/.docker/cli-plugins/docker-buildx
    - docker buildx create --name travis_builder --use

  - &run-docker-tests
    - set -e
    - cd docker
    - make lint
    - make build
    - make test

  - &after-docker-tests
    - docker buildx rm travis_builder

jobs:
  include:
    # === container tests
    - stage: ❧ pdb tests
      name: container tests
      dist: focal
      language: ruby
      rvm: 2.6.6
      services: docker
      # necessary to prevent overwhelming TravisCI build output limits
      env: DOCKER_COMPOSE_VERSION=1.28.6 DOCKER_BUILDX_VERSION=0.5.1 DOCKER_BUILD_FLAGS="--progress plain" PUPPETSERVER_IMAGE="puppet/puppetserver:edge"
      before_install: *before-docker-tests
      script: *run-docker-tests
      after_script: *after-docker-tests

on_success: ci/bin/travis-on-success

notifications:
  email: false
  slack:
    template:
      - "<%{compare_url}|%{commit_subject}> | %{author}"
      - "%{repository_slug} %{branch} | <%{build_url}|#%{build_number}> %{result} in %{elapsed_time}"
    rooms:
      secure: IJU0YgGYbKgM7NupaOmE2BYra2mNx7+e5vAYNL+5oaRXolbHCyg0WzfFWilhMK3KEi8oIMKXR4ZzoUZLAqeOQzX7nnsLqC3wjyDHCgxtp4O+5GNKyeLN4ItoI1f2d6qyiiBPkHgVPuLhG3yyQ+wD0dMc9vSYmxfoazqe9HD/9UE=

cache:
  directories:
    - /var/cache/apt/archives
    - $HOME/.m2
    - $HOME/Library/Caches/Homebrew
    - ci/local/jdk
    - vendor/bundle/ruby
