#!/usr/bin/env bash

set -e

jar="${PDB_JAR:-target/puppetdb.jar}"

if test "$BCPROV_JAR"; then
    bcprov="$BCPROV_JAR"
else
    bcprov_ver=$(lein deps :query org.bouncycastle/bcprov-jdk15on 2>/dev/null)
    bcprov="$HOME/.m2/repository/org/bouncycastle/bcprov-jdk15on/$bcprov_ver/bcprov-jdk15on-$bcprov_ver.jar"
fi

if test "$BCPKIX_JAR"; then
    bcpkix="$BCPKIX_JAR"
else
    bcpkix_ver=$(lein deps :query org.bouncycastle/bcpkix-jdk15on 2>/dev/null)
    bcpkix="$HOME/.m2/repository/org/bouncycastle/bcpkix-jdk15on/$bcpkix_ver/bcpkix-jdk15on-$bcpkix_ver.jar"
fi

if ! test -e "$jar"; then
    printf 'Unable to find the puppetdb jar %q; have you run "lein uberjar"?\n' \
           "$jar" 1>&2
    exit 2
fi

if ! test -e "$bcprov"; then
    printf 'Unable to find the bouncy castle provider jar %q; have you run "lein deps"?\n' \
           "$bcprov" 1>&2
    exit 2
fi

if ! test -e "$bcpkix"; then
    printf 'Unable to find the bouncy castle provider jar %q; have you run "lein deps"?\n' \
           "$bcpkix" 1>&2
    exit 2
fi

exec java -cp "$jar:$bcprov:$bcpkix" clojure.main -m puppetlabs.puppetdb.core "$@"
