name    'puppetlabs-puppetdb'
version '0.0.1'
source 'UNKNOWN'
author 'puppetlabs'
license 'UNKNOWN'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'puppetlabs/nginx', '0.0.1'
