#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
from puppetdb import PuppetDB

if __name__ == '__main__':
    pdb = PuppetDB()
    subcommand = sys.argv[1]
    if subcommand == 'simulate':
        args = sys.argv[2:]
        if len(args) == 2:
            nhosts, interval = args
            pdb.simulate(int(nhosts), int(interval))
        elif len(args) == 3:
            nhosts, interval, orphans = args
            # bool(orphans) below will be set to True on any non empty string
            pdb.simulate(int(nhosts), int(interval), bool(orphans))
        else:
            raise ValueError('called with unsupported number of args')

    if subcommand == 'query':
        pdb.query(sys.argv[2])
