#!/usr/bin/env python

from __future__ import print_function
from sys import exit, stderr
import os, platform, sys

def usage(stream):
    print('Usage: pgbin-from-spec core/openjdk8/pg9.6', file=stream)

def misuse():
    usage(stderr)
    exit(2)
        
len(sys.argv) == 2 or misuse()
specs = sys.argv[1]
specs = specs.split('/')
specs = [x for x in specs if x.startswith('pg-')]
len(specs) == 1 or misuse()

if platform.system() == 'Linux':
    print('/usr/lib/postgresql/%s/bin' % specs[0][len('pg-'):])
else:
    # assume osx/homebrew
    print('/usr/local/opt/postgresql@%s/bin' % specs[0][len('pg-'):])
