#!/usr/bin/env bash

set -uxeo pipefail

usage() {
    echo "Usage: $(basename "$0") PUPPET_REF PUPPETSERVER_REF"
}

if test $# -ne 2; then
    usage 1>&2
    exit 2
fi

pup_ref="$1"
pupsrv_ref="$2"

ulimit -u 4096
java -version
lein version

ext/bin/config-puppet-test-ref "$pup_ref"
ext/bin/config-puppetserver-test-ref "$pupsrv_ref"

pgdir="$(pwd)/test-resources/var/pg"
export PGHOST=127.0.0.1
export PGPORT=5432
ext/bin/setup-pdb-pg "$pgdir"
ext/bin/pdb-test-env "$pgdir" lein test :integration
