#!/usr/bin/env python

from __future__ import print_function
from sys import exit, stderr
import os, sys

def usage(stream):
    print('Usage: spec-includes .../pup-5.3.x/srv-5.1.x/something something',
          file=stream)

def misuse():
    usage(stderr)
    exit(2)

len(sys.argv) == 3 or misuse()
specs, what = sys.argv[1:]
specs = specs.split('/')
if what in specs:
    print(what)
